palavras_faceis = [ 'amor', 'fato', 'puta', 'mito', 'esmo', 'caos', 
                   'brio', 'vide', 'não', 'auge', 'como', 'sede', 
                   'céu', 'pois', 'ermo', 'mote', 'apto', 'tolo', 
                   'suma', 'crer', 'vida', 'vão', 'saga', 'idem', 
                   'medo', 'veio', 'cota', 'urge', 'zelo', 'pude', 
                   'ruim', 'mãe', 'coxo', 'ente', 'ater', 'soar', 
                   'réu', 'fase', 'gozo', 'casa', 'sina', 'rude', 
                   'rima', 'voga', 'cujo', 'cedo', 'onde', 'sela', 
                   'mais', 'foda', 'pela', 'nojo', 'meio', 'cela', 
                   'teor', 'auto', 'tudo', 'face', 'para', 'pose', 
                   'ante', 'base', 'teve', 'asco', 'jugo', 'numa', 
                   'alvo', 'logo', 'traz', 'alva', 'agir', 'vale', 
                   'são', 'nexo', 'meta', 'amar', 'todo', 'eita', 
                   'rege', 'orla', 'alta', 'rito', 'mero', 'doce', 
                   'pelo', 'alto', 'foco', 'deus', 'sair', 'arte', 
                   'tese', 'bojo', 'até', 'novo', 'fora', 'alma', 
                   'nós', 'lume', 'fito', 'seio' ]

palavras_normal = ['empatia', 'embuste', 'prolixo', 'cínico', 
                   'idôneo', 'âmbito', 'sublime', 'néscio', 
                   'índole', 'sucinto', 'inócuo', 'convém', 
                   'verbete', 'recesso', 'inferir', 'cinismo', 
                   'ênfase', 'refutar', 'mérito', 'sádico', 
                   'alusão', 'redimir', 'cordial', 'exortar', 
                   'emergir', 'trivial', 'imputar', 'exímio', 
                   'afável', 'aspecto', 'virtude', 'candura', 
                   'deboche', 'mitigar', 'cultura', 'almejar', 
                   'adesão', 'soberba', 'excerto', 'seção', 
                   'sóbrio', 'dádiva', 'ademais', 'oriundo', 
                   'austero', 'fomento', 'cético', 'alegria', 
                   'excesso', 'contudo', 'lábaro', 'sensato', 
                   'paixão', 'apreço', 'conciso', 'júbilo', 
                   'sessão', 'exilado', 'sucesso', 'alcunha', 
                   'otário', 'êxtase', 'salutar', 'clichê', 
                   'padecer', 'colosso', 'ímpeto', 'modesto', 
                   'auferir', 'ansioso', 'hábito', 'quimera', 
                   'estirpe', 'emotivo', 'intenso', 'estrupo', 
                   'cessão', 'também', 'glória', 'coragem', 
                   'exílio', 'parcial', 'hesitar', 'demanda', 
                   'alçada', 'indagar', 'ousadia', 'incauto', 
                   'assento', 'mancebo', 'piedade', 'vigente', 
                   'lúdico', 'intuito', 'profano', 'colapso', 
                   'sentido', 'orgulho', 'bizarro', 'cortês']

palavras_dificeis = ['significado', 'perspectiva', 'dicionário', 
                     'intrínseco', 'presunçoso', 'dissimulado', 
                     'diligência', 'intempérie', 'presunção', 
                     'concepção', 'complacente', 'parcimônia', 
                     'vicissitude', 'referência', 'contundente', 
                     'inexorável', 'arbitrário', 'expectativa', 
                     'pragmático', 'indiferente', 'beligerante', 
                     'pretensioso', 'pressuposto', 'incidência', 
                     'descrição', 'suscetível', 'retrógrado', 
                     'transcender', 'contingente', 'discrição', 
                     'contencioso', 'anacrônico', 'concernente', 
                     'proeminente', 'excêntrico', 'indolência', 
                     'superficial', 'ingerência', 'antagonismo', 
                     'intensidade', 'escrutínio', 'necessidade', 
                     'preconceito', 'restrição', 'infortúnio', 
                     'excelência', 'resolução', 'benignidade', 
                     'signatário', 'pecuniária', 'esplêndido', 
                     'reivindicar', 'espontâneo', 'percepção', 
                     'supracitado', 'cumprimento', 'compreender', 
                     'itinerário', 'proveniente', 'aquisição', 
                     'pernóstico', 'convicção', 'benevolente', 
                     'necessário', 'privilégio', 'verossímil', 
                     'animosidade', 'subsequente', 'displicente', 
                     'fleumático', 'exortação', 'pusilânime', 
                     'relevância', 'inferência', 'contenção', 
                     'ambiguidade', 'esporádico', 'estabelecer', 
                     'conveniente', 'oportunista', 'identificar', 
                     'interação', 'militância', 'abominável', 
                     'discriminar', 'generalizar', 'tergiversar', 
                     'constância', 'sarcástico', 'enigmático', 
                     'distinção', 'desgraçado', 'influência', 
                     'verborragia', 'subordinado', 'integridade', 
                     'expedição', 'perdulário', 'austeridade', 
                     'específico']

vogal_a = ['a', 'á', 'à', 'â', 'ã']
 
vogal_e = ['e', 'é', 'è', 'ê']

vogal_i = ['i', 'í', 'ì']

vogal_o = ['o', 'ó', 'ò', 'ô', 'õ']

vogal_u = ['u', 'ú', 'ù']
